sf_end_points = {
    "contact": {
        "endpoint": "/services/data/v58.0/jobs/query",
        "extract_type": "custom",
        "request_type": "POST",
        "paging": False,
        "cursor": False,
        "interval": False,
        "params": {"pageSize": 1000},
        "entity_name": "contact",
        "spark_partitions": {"max_records_per_partition": 5000},
        "table_name": "contact",
        "tbl_overwrite": False,
    },
    "account": {
        "endpoint": "/services/data/v58.0/jobs/query",
        "extract_type": "custom",
        "request_type": "POST",
        "paging": False,
        "cursor": False,
        "interval": False,
        "params": {"pageSize": 1000},
        "entity_name": "account",
        "spark_partitions": {"max_records_per_partition": 5000},
        "table_name": "account",
        "tbl_overwrite": False,
    },
    "case": {
        "endpoint": "/services/data/v58.0/jobs/query",
        "extract_type": "custom",
        "request_type": "POST",
        "paging": False,
        "cursor": False,
        "interval": False,
        "params": {"pageSize": 1000},
        "entity_name": "case",
        "spark_partitions": {"max_records_per_partition": 5000},
        "table_name": "case",
        "tbl_overwrite": False,
    },
    "event": {
        "endpoint": "/services/data/v58.0/jobs/query",
        "extract_type": "custom",
        "request_type": "POST",
        "paging": False,
        "cursor": False,
        "interval": False,
        "params": {"pageSize": 1000},
        "entity_name": "event",
        "spark_partitions": {"max_records_per_partition": 5000},
        "table_name": "event",
        "tbl_overwrite": False,
    },
    "lead": {
        "endpoint": "/services/data/v58.0/jobs/query",
        "extract_type": "custom",
        "request_type": "POST",
        "paging": False,
        "cursor": False,
        "interval": False,
        "params": {"pageSize": 1000},
        "entity_name": "lead",
        "spark_partitions": {"max_records_per_partition": 5000},
        "table_name": "lead",
        "tbl_overwrite": False,
    },
    "order": {
        "endpoint": "/services/data/v58.0/jobs/query",
        "extract_type": "custom",
        "request_type": "POST",
        "paging": False,
        "cursor": False,
        "interval": False,
        "params": {"pageSize": 1000},
        "entity_name": "order",
        "spark_partitions": {"max_records_per_partition": 5000},
        "table_name": "order",
        "tbl_overwrite": False,
    },
    "task": {
        "endpoint": "/services/data/v58.0/jobs/query",
        "extract_type": "custom",
        "request_type": "POST",
        "paging": False,
        "cursor": False,
        "interval": False,
        "params": {"pageSize": 1000},
        "entity_name": "task",
        "spark_partitions": {"max_records_per_partition": 5000},
        "table_name": "task",
        "tbl_overwrite": False,
    },
    "opportunity": {
        "endpoint": "/services/data/v58.0/jobs/query",
        "extract_type": "custom",
        "request_type": "POST",
        "paging": False,
        "cursor": False,
        "interval": False,
        "params": {"pageSize": 1000},
        "entity_name": "opportunity",
        "spark_partitions": {"max_records_per_partition": 5000},
        "table_name": "opportunity",
        "tbl_overwrite": False,
    },
}