# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- None

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Pay-As-You-Go(590f7ac0-b909-4092-adb4-2ad447a5bb19)'
    ScriptType: 'InlineScript'
    Inline: |
      azcopy --version
      azcopy --help
    azurePowerShellVersion: 'LatestVersion'