import json
# from dganalytics.ssis_replacement.tenants.holden import ( 
#     mongo_pipelines as pipelines ,
#     source_data_schemas as schemas
#     )
from . import ( 
    mongo_pipelines as pipelines ,
    source_data_schemas as schemas
    )
from copy import deepcopy
import logging

config = {
    # "run_window_type": "FIXED",
    "run_window_type": None,
    # "find_min_rundate": {
    #     "collections": [
    #         'CENTERVIEW',
    #         'ADVISORVIEW',
    #         'QADATA',
    #         'USERIDMAP',
    #         'TIMEUTILISATION',
    #         'NPS&CSAT',
    #         'QASLA',
    #     ],
    #     "pipeline": pipelines.aaa_get_dates.aggr_pipeline,
    #     'load_timestamp_field': "insertion_timestamp",
    # },
    "Center_View": { #uniqu key is not available
        
        'output_collxn': "t_CCP_Center_view",
        'pipeline': pipelines.stage1_Center_View.aggr_pipeline,
        'collection': "CENTERVIEW",
        'load_timestamp_field': "insertion_timestamp",
        'output_columns': [
            'Date',
            'Buisness_Unit',
            'ACD_Calls',
            'Direct_Agent_Calls',
            'Ext_Out_Calls',
            'Total_ACD_Time_m',
            'Max_Delay_m',
            'Abn_Calls',
            'Avg_Outbound_Time_m',
            'Trans_Out',
            'Avg_Handle_Time_m',
            'ABN',
            'Total_ACW_Time_m',
            'OCCP_includes_AUX_7',
            'OCCP_AUX_7_9',
            'Total_Outbound_Time_min',
            'Avg_ACW_Time_m',
            'AVG_ABN_Time_m',
            'Avg_ACD_Time_m',
            'Avg_Speed_Ans_s',
            'Service_Level',
            'Total_Handle_Time_m',
            'AUX_8_m',
            'AUX_7_m',
            'OCCP',
            'AUX_9_m',
            'Total_Avail_Time_m',
            'Total_Hold_Time_m',
            'AUX_6_m',
            'AUX_5_m',
            'Avg_Hold_Time_m',
            'runID',
            'org_id',
            'transport_time'
        ],
        'primary_key': [
            'Date',
            'Buisness_Unit',
        ],
        'output_type': ['MERGED'],
        'partition_by': "Date",
        'schema': schemas.Center_View.schema
    },
    "Advisor_view": {
        'output_collxn': "t_CCP_Advisor_view",
        'pipeline': pipelines.stage2_Advisor_view.aggr_pipeline,
        'collection': "ADVISORVIEW",
        'load_timestamp_field': "insertion_timestamp",
        'output_columns': [
            'AUX_1_min',
            'Out_Calls',
            'AUX_0_min',
            'AUX_3_min',
            'AUX_2_min',
            'Direct_Agent_Calls',
            'Avail_Time_min',
            'Total_Hold_Time_min',
            'Average_ACW_Time_min',
            'Average_Handle_Time_min',
            'Average_Hold_Time_min',
            'Total_ACD_Time_min',
            'AUX_9_min',
            'AUX_8_min',
            'AUX_5_min',
            'AUX_4_min',
            'AUX_7_min',
            'Date',
            'AUX_6_min',
            'Login_ID',
            'Staffed_Time_min',
            'AUX_Time_min',
            'Average_ACD_Time_min',
            'Total_ACW_Time_min',
            # '$login_name',
            'ACD_Calls',
            'Delivered_Time_min',
            'Total_Handle_Time_min',
            'Login_Name',
        ],
        'primary_key': [
            'Date',
            'Login_Name',
            'Login_ID',
        ],
        'output_type': ['MERGED'],
        'partition_by': 'Date',
        'schema': schemas.Advisor_view.schema
    },
    "QA_Data_ETL": {
        
        'output_collxn': 't_QA_DATA',
        'collection': 'QADATA',
        'load_timestamp_field': "insertion_timestamp",
        'pipeline': pipelines.stage3_QA_Data_ETL.aggr_pipeline,
        'output_columns': [
            'Q5_c_Goodwill_Has_this_section_and_relevant_activities_been_completed_correctly', 
            'Q5_d_Attachments_Have_the_all_critical_attachments_and_approvals_been_attached_to_the_front_of_th',
            'Agent_Name', 
            'Advisor_Status', 
            'Channel', 
            'Q2_Interaction_Notes_Transcript_Link', 
            'Q3_b_Were_all_written_comms_to_the_customer_accurate_easily_understandable_address_the_customer', 
            'Q3_g_Did_the_advisor_send_a_CSAT_to_the_customer_if_appropriate', 
            'Evaluation_Method', 
            'Q4_b_Did_the_advisor_engage_the_appropriate_stakeholders_and_record_provide_all_relevant_informatio', 
            'Q3_c_Did_the_advisor_demonstrate_the_usage_of_appropriate_soft_skills', 
            'Q3_Customer_Interactions', 
            'Q4_c_Did_the_advisor_summarise_all_case_notes_templates_accurately_to_reflect_the_discussion_on', 
            'Q1_Reporting_Detail', 
            'General_Data', 
            'Evaluator_Name', 
            'Evaluation_Date', 
            'Q3_d_Did_the_advisor_advocate_for_the_brand_provide_a_good_customer_experience', 
            'Proportional_Score', 
            'Comments', 
            'Q3_e_Did_the_advisor_make_commitments_respond_to_all_the_customers_interactions_within_the_requir', 
            'Q1_a_Capture_case_number_Enter_in_pop_up_notes_field', 
            'Q3_a_Did_the_advisor_understand_the_customer_s_problem_to_solve_as_well_as_their_desired_outcome', 
            'Q3_f_Was_all_the_required_information_outcome_provided_to_the_customer_accurate', 
            'Case_Type', 
            'Interaction_ID', 
            'Sections_Questions', 
            'Q5_b_Rental_Requests_Has_this_section_and_relevant_activities_been_completed_correctly', 
            'Orig_Calib', 
            'Evaluation_Score', 
            'Q6_a_Has_the_advisor_followed_all_company_policies_and_ensured_that_Holden_is_compliant_with_the_re', 
            'Q5_a_Have_the_SR_Customer_Vehicle_Dealer_Additional_Information_fields_been_filled_out_and_ar', 
            'Q4_a_Did_the_advisor_do_everything_in_their_control_to_investigate_progress_the_customers_concern', 
            'User_ID', 
            'Q4_Investigation_Case_Notes', 
            'Q5_Service_Request_Admin', 
            'Q6_Overall',
        ],
        'primary_key': [
            'User_ID', 
            'Evaluation_Date', 
        ],
        'output_type': ['MERGED'],
        'partition_by': 'Evaluation_Date',
        'schema': schemas.QA_Data_ETL.schema
    },
    "USERID_MAP": {
        
        'output_collxn': 't_USERIDMAP',
        'collection': 'USERIDMAP',
        'load_timestamp_field': "insertion_timestamp",
        'pipeline': pipelines.stage4_USERID_MAP.aggr_pipeline,
        'output_columns': [
            'Full_Name', 
            'Role', 
            'Buisness_Unit', 
            'Litmus_ID', 
            'Avaya_ID', 
            'Last_Name', 
            'IEX_ID', 
            'Team_Leader', 
            'First_Name', 
            'Email', 
            'QA_ID', 
            'Status'
        ],
        'primary_key': [
            'First_Name', 
            'Last_Name', 
            'Full_Name', 
            'Email', 
        ],
        'output_type': ['MERGED'],
        'partition_by': None,
        'schema': schemas.USERID_MAP.schema
    },
    "Time_Utilisation": {
        
        'output_collxn': 't_ccp_time_util',
        'collection': 'TIMEUTILISATION',
        'load_timestamp_field': "insertion_timestamp",
        'pipeline': pipelines.stage5_Time_Utilisation.aggr_pipeline,
        'output_columns': [
            '_id',
            # 'exist_id'
            'Exception',
            'Agent_Name',
            'UPA',
            'Non_UPA',
            'IEX_ID',
            'Time',
            'Total_Time_mins',
            'Shot_Date',
            'User_ID',
            'Break',
            'Lunch',
        ],
        'primary_key': [ 
            '_id',
            'Shot_Date',
            'IEX_ID',
            # 'exist_id'
         ],
        'output_type': ['MERGED'],
        'partition_by': 'Shot_Date',
        'schema': schemas.Time_Utilisation.schema
    },
    "NPS_CSAT": {
        
        'output_collxn': 't_CCP_NPS_CSAT',
        'load_timestamp_field': "insertion_timestamp",
        'collection': 'NPS&CSAT',
        'pipeline': pipelines.stage6_NPS_CSAT.aggr_pipeline,
        'output_columns': [
            'Sentiment', 
            'Invitation_Id', 
            'Promoter_channel', 
            'Service_request_number', 
            'Team_Leader', 
            'Fast_Lane', 
            'Primary_Question_Based_on_your_recent_interaction_how_likely_are_you_to_recommend_Holden_to_a_colleague_friend_or_family_member', 
            'SR_Owner', 
            'Sub_Categories', 
            'Opened_Time', 
            'Days_between_opened_and_re_opened', 
            'Has_the_reason_for_your_contact_with_Holden_Customer_Care_been_resolved', 
            'Trial_1', 
            'Service_Request', 
            'How_satisfied_you_are_with_the_service_you_have_received_from_the_Advisor', 
            'Responded_on', 
            'Group_Group', 
            'Last_Complete_Date', 
            'Case_Type', 
            'When_can_we_contact_you_to_discuss_this_further', 
            'Primary_Comment_Comment', 
            'Touchpoint_name', 
            'Last_Active_Date', 
            'Request_Date', 
            'Group_Brand', 
            'Rated_Medium', 
            'Responded_Using', 
            'Country_code',
        ],
        'primary_key': [ 
            'Touchpoint_name',
            'Responded_on', 
            'Invitation_Id', 
        ],
        'output_type': ['MERGED'],
        'partition_by': 'Responded_on',
        'schema': schemas.NPS_CSAT.schema
    },
    "QA_SLA_ETL": { 
        
        'output_collxn': 't_zQA_SLA',
        'collection': 'QASLA',
        'load_timestamp_field': "insertion_timestamp",
        'pipeline': pipelines.stage7_QA_SLA_ETL.aggr_pipeline,
        'output_columns': [
            'Evaluated_Name',
            'Evaluation_Creation_Date',
            'Reviewd_by_evaluator',
            'Type',
            'Evaluator_Review_Date',
            'Reviewed_By_Agent',
            'Evaluation_Modification_Date',
            'Score',
            'Evaluation_comment',
            'Evaluator_Name',
            'Segment_ID_Attached_to_Evaluation',
            'Agent_Review_Date',
            'Form_Name',
            'Max_Score',
        ],
        'primary_key': [
            'Evaluated_Name',
            'Evaluation_Creation_Date',
            'Type',
            'Evaluator_Review_Date',
            'Evaluation_Modification_Date',
            'Evaluator_Name',
            'Segment_ID_Attached_to_Evaluation',
            'Agent_Review_Date',
        ],
        'output_type': ['MERGED'],
        'partition_by': 'Evaluator_Review_Date',
        'schema': schemas.QA_SLA_ETL.schema
    },
    "EMAIL_SOCIAL_SLA": {
        'output_collxn': "t_EMAIL_SOCIAL_SLA",
        'pipeline': pipelines.stage8_EMAIL_SOCIAL_SLA.aggr_pipeline,
        'collection': "EMAIL&SOCIALSLA",
        'load_timestamp_field': "insertion_timestamp",
        'output_columns': [
            'runID',
            'Report_Date',
            'Oldest_HCC_Email',
            'Oldest_Recall_Email',
            'Oldest_Social_Post',
            'transport_time',
        ],
        'primary_key': [
            'Report_Date',
        ],
        'output_type': ['MERGED'],
        'partition_by': None,
        'schema': schemas.EMAIL_SOCIAL_SLA.schema
    },
    "CCP_Interval_Report": {
        'output_collxn': "t_CCP_Interval_Report",
        'pipeline': pipelines.stage9_CCP_Interval_Report.aggr_pipeline,
        'collection': "INTERVAL",
        'load_timestamp_field': "insertion_timestamp",
        'output_columns': [
            'Login_ID',
            'Time',
            'date',
            'ACD_Calls',
            'Direct_Agent_Calls',
            'DA_Abandon',
            'DA_Other',
            'Extout_Calls',
            'CARS_ACD_min',
            'CARS_Hold_min',
            'ACW_min',
            'THT_min',
            'Outbound_Time_min',
            'True_ACW_min',
            'Total_Stafftime_min',
            'Total_Auxtime_min',
            'Avail_Time',
            'AUX_1_min',
            'AUX_2_min',
            'AUX_3_min',
            'AUX_4_min',
            'AUX_5_min',
            'AUX_6_min',
            'Aux_7_min',
            'AUX_8_min',
            'AUX_9_min',
            'transport_time',
        ],
        'primary_key': [
            'Login_ID',
            'Time',
            'date',
        ],
        'output_type': ['MERGED'],
        'partition_by': None,
        'schema': schemas.CCP_Interval_Report.schema
    },
}
