aggr_pipeline = [
  {
    "$project": {
      "_id":0,
      'AUX_1_min':'$aux1',
      'Out_Calls':'$out_calls',
      'AUX_0_min':'$aux0',
      'AUX_3_min':'$aux3',
      'AUX_2_min':'$aux2',
      'Direct_Agent_Calls':'$direct_agent_calls',
      'Avail_Time_min':'$avail_time',
      'Total_Hold_Time_min':'$tot_hold_time',
      'Average_ACW_Time_min':'$avg_acw_time',
      'Average_Handle_Time_min':'$avg_handle_time',
      'Average_Hold_Time_min':'$avg_hold_time',
      'Total_ACD_Time_min':'$tot_acd_time',
      'AUX_9_min':'$aux9',
      'AUX_8_min':'$aux8',
      'AUX_5_min':'$aux5',
      'AUX_4_min':'$aux4' ,
      'AUX_7_min':'$aux7',
      'Date':'$report_date',
      'AUX_6_min':'$aux6',
      'Login_ID':'$login_id',
      'Staffed_Time_min':'$staffed_time',
      'AUX_Time_min':'$aux_time',
      'Average_ACD_Time_min':'$avg_acd_time',
      'Total_ACW_Time_min':'$tot_acw_time',
      # '$login_name',
      'ACD_Calls':'$acd_calls',
      'Delivered_Time_min':'$delivered_time',
      'Total_Handle_Time_min':'$tot_handle_time',
      'Login_Name':'$user_id',
      # '$runID',
      # '$org_id',
    }
  }
]