from  . import Raw_FCR
from  . import User_FCR_KPI_Data
from  . import User_AHT_KPI_Data
from  . import Call_Volume
from  . import User_Details
from  . import JSR_Process_Forecast_Data
from  . import JSR_KPI_Team_Target
from  . import User_KPI_Data
from  . import JSR_Top_Reason_Data
from  . import JSR_Process_TNPS_KPI_Data_to_All_Process
from  . import Process_AHT_KPI_Data_to_All_Process
from  . import JSR_Process_KPI_Data_to_All_Process
from  . import JSR_Process_FCR_KPI_to_All_Process
from  . import Admin_Login
from  . import JSR_AHT_KPI_Data
from  . import JSR_Trouble_Ticket_Data
from  . import JSR_Process_KPI_Data
