"""
Api configuration for Nice inContact
This module contains the API configuration for Nice inContact, including endpoints, request types
"""

niceincontact_end_points = {
    "agents": {
        "endpoint": "/incontactapi/services/v32.0/agents",
        "request_type": "GET",
        "paging": False,
        "interval": False,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "agents",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "agents_groups": {
        "endpoint": "/incontactapi/services/v32.0/agents/{agentId}/groups",
        "request_type": "GET",
        "paging": False,
        "interval": False,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "agentGroups",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "agents_skills": {
        "endpoint": "/incontactapi/services/v32.0/agents/skills",
        "request_type": "GET",
        "paging": False,
        "interval": False,
        "params": {
            "isActive": True,
            "isAgentActive": True,
        },
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "agentSkillAssignments",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "groups": {
        "endpoint": "/incontactapi/services/v32.0/groups",
        "request_type": "GET",
        "paging": True,
        "interval": False,
        "params": {"pageSize": 500},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "agents",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "groups_agents": {
        "endpoint": "/incontactapi/services/v32.0/groups/{groupId}/agents",
        "request_type": "GET",
        "paging": True,
        "interval": False,
        "params": {"pageSize": 500},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "agents",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "teams": {
        "endpoint": "/incontactapi/services/v32.0/teams",
        "request_type": "GET",
        "paging": True,
        "interval": False,
        "params": {"pageSize": 500},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "teams",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "teams_Id_agents": {
        "endpoint": "/incontactapi/services/v32.0/teams/{teamId}/agents",
        "request_type": "GET",
        "paging": True,
        "interval": False,
        "params": {"pageSize": 500},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "teams",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "teams_agents": {
        "endpoint": "/incontactapi/services/v32.0/teams/agents",
        "request_type": "GET",
        "paging": False,
        "interval": False,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "teams",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "schedules_export": {
        "endpoint": "/incontactapi/services/v32.0/schedules/export",
        "request_type": "POST",
        "paging": False,
        "interval": True,
        "entity_name": "agentSchedules",
        "spark_partitions": {"max_records_per_partition": 20000},
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "wfm_data_agents": {
        "endpoint": "/incontactapi/services/v32.0/wfm-data/agents",
        "request_type": "GET",
        "paging": False,
        "interval": True,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "wfoAgentSpecificStats",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "wfm_data_agents_schedule_adherence": {
        "endpoint": "/incontactapi/services/v32.0/wfm-data/agents/schedule-adherence",
        "request_type": "GET",
        "paging": False,
        "interval": True,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "agentStateHistory",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "wfm_data_agents_scorecards": {
        "endpoint": "/incontactapi/services/v32.0/wfm-data/agents/scorecards",
        "request_type": "GET",
        "paging": False,
        "interval": True,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "wfmScorecardStats",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "wfm_data_skills_agent_performance": {
        "endpoint": "/incontactapi/services/v32.0/wfm-data/skills/agent-performance",
        "request_type": "GET",
        "paging": False,
        "interval": True,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "tbl_overwrite": False,
        "entity_name": "skillsPerformance",
        "raw_primary_key": ["id"],
    },
    "wfm_data_skills_contacts": {
        "endpoint": "/incontactapi/services/v32.0/wfm-data/skills/contacts",
        "request_type": "GET",
        "paging": False,
        "interval": True,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "tbl_overwrite": False,
        "entity_name": "contactStats",
        "raw_primary_key": ["id"],
    },
    "wfm_data_skills_dialer_contacts": {
        "endpoint": "/incontactapi/services/v32.0/wfm-data/skills/dialer-contacts",
        "request_type": "GET",
        "paging": False,
        "interval": True,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "outboundStats",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "agents_interaction_history": {
        "endpoint": "/incontactapi/services/v32.0/agents/interaction-history",
        "request_type": "GET",
        "paging": True,
        "interval": True,
        "params": {"pageSize": 500},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "contactStates",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "agents_performance": {
        "endpoint": "/incontactapi/services/v32.0/agents/performance",
        "request_type": "GET",
        "paging": False,
        "interval": True,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "agentPerformance",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "contacts": {
        "endpoint": "/incontactapi/services/v32.0/contacts",
        "request_type": "GET",
        "paging": True,
        "interval": True,
        "params": {"pageSize": 500},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "contacts",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "contacts_smstranscripts": {
        "endpoint": "/incontactapi/services/v32.0/contacts/sms-transcripts",
        "request_type": "GET",
        "paging": True,
        "interval": True,
        "params": {"pageSize": 500},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "smsTranscripts",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "contacts_completed": {
        "endpoint": "/incontactapi/services/v32.0/contacts/completed",
        "request_type": "GET",
        "paging": True,
        "interval": True,
        "params": {"pageSize": 500},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "completedContacts",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "contacts_custom_data": {
        "endpoint": "/incontactapi/services/v32.0/contacts/custom-data",
        "request_type": "GET",
        "paging": True,
        "interval": True,
        "params": {"pageSize": 500},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "ContactCustomData",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "skills_summary": {
        "endpoint": "/incontactapi/services/v32.0/skills/summary",
        "request_type": "GET",
        "paging": False,
        "interval": True,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "skillSummaries",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "skills_sla_summary": {
        "endpoint": "/incontactapi/services/v32.0/skills/sla-summary",
        "request_type": "GET",
        "paging": False,
        "interval": False,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "serviceLevelSummaries",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "teams_performance": {
        "endpoint": "/incontactapi/services/v32.0/teams/performance-total",
        "request_type": "GET",
        "paging": False,
        "interval": True,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "teamPerformanceTotal",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "data_extraction_jobs": {
        "endpoint": "/data-extraction/v1/jobs/{jobId}",
        "request_type": "GET",
        "paging": False,
        "interval": False,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "result",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "media_playback_contact": {
        "endpoint": "/media-playback/v1/contacts",
        "request_type": "GET",
        "paging": False,
        "interval": False,
        "params": {
            "media-type": ["voice-only", "voice-and-screen", "chat", "email"],
            "exclude-waveforms": True,
            "exclude-qm-categories": False,
            "isDownload": False
        },
        "spark_partitions": {
            "max_records_per_partition": 20000
        },
        "entity_name": "mediaPlaybackContacts",
        "tbl_overwrite": False,
        "raw_primary_key": ["acd-call-id"]
    },
    "segments_analyzed_transcript": {
        "endpoint": "/interaction-analytics-gateway/v2/segments/{segmentId}/analyzed-transcript",
        "request_type": "GET",
        "paging": False,
        "interval": False,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "skills": {
        "endpoint": "/incontactapi/services/v32.0/skills",
        "request_type": "GET",
        "paging": False,
        "interval": False,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "skills",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "dispositions": {
        "endpoint": "/incontactapi/services/v32.0/dispositions",
        "request_type": "GET",
        "paging": False,
        "interval": False,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "dispositions",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "dispositions_skills": {
        "endpoint": "/incontactapi/services/v32.0/dispositions/skills",
        "request_type": "GET",
        "paging": False,
        "interval": False,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "dispositions",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "contacts_contactId_email_transcript": {
        "endpoint": "/incontactapi/services/v32.0/contacts/{{contactId}}/email-transcript",
        "request_type": "GET",
        "paging": False,
        "interval": False,
        "params": {},
        "spark_partitions": {"max_records_per_partition": 20000},
        "entity_name": "dispositions",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"],
    },
    "segments_analyzed": {
        "endpoint": "/interaction-analytics-gateway/v2/segments/analyzed",
        "request_type": "GET",
        "paging": False,
        "cursor": True,
        "interval": True,
        "params": {
            "pageSize": 1000,
            "order": "asc"
        },
        "spark_partitions": {
            "max_records_per_partition": 20000
        },
        "entity_name": "interactions",
        "tbl_overwrite": False,
        "raw_primary_key": ["id"]
    },
    "media_playback_chat_email_segment": {
        "endpoint": "/media-playback/v1/segments/{segmentId}",
        "request_type": "GET",
        "paging": False,
        "interval": False,
        "params": {
            "media-type": ["voice-only", "voice-and-screen", "chat", "email", "all"],
            "exclude-waveforms": True,
            "exclude-qm-categories": False
        },
        "spark_partitions": {
            "max_records_per_partition": 20000
        },
        "entity_name": "interactions",
        "tbl_overwrite": False,
        "raw_primary_key": ["segmentId"]
    },
    "media_playback_voice_segment": {
        "endpoint": "/media-playback/v1/segments/{segmentId}",
        "request_type": "GET",
        "paging": False,
        "interval": False,
        "params": {
            "media-type": ["voice-only", "voice-and-screen", "chat", "email", "all"],
            "exclude-waveforms": True,
            "exclude-qm-categories": False
        },
        "spark_partitions": {
            "max_records_per_partition": 20000
        },
        "entity_name": "interactions",
        "tbl_overwrite": False,
        "raw_primary_key": ["segmentId"]
    }
}
