keyword_map = """
create temp view keyword_map
as
select col[0] as region, col[1] as wrapcode, col[2] as keyword
from (select explode(array(array("AU","Account - 1st Box Change / Question","day"),
array("AU","Account - 1st Box Change / Question","box type"),
array("AU","Account - 1st Box Change / Question","query"),
array("NZ","Account - 1st Box Change / Question","cancellation"),
array("AU","Account - 1st Box Change / Question","address"),
array("NZ","Account - 1st Box Change / Question","address"),
array("NZ","Account - 1st Box Change / Question","change"),
array("AU","Account - 1st Box Change / Question","change"),
array("AU","Account - 1st Box Change / Question","price"),
array("NZ","Account - 1st Box Change / Question","price"),
array("NZ","Account - 1st Box Change / Question","delivery"),
array("NZ","Account - 1st Box Change / Question","box type"),
array("NZ","Account - 1st Box Change / Question","query"),
array("AU","Account - 1st Box Change / Question","week"),
array("NZ","Account - 1st Box Change / Question","week"),
array("AU","Account - 1st Box Change / Question","cancellation"),
array("AU","Account - 1st Box Change / Question","delivery"),
array("NZ","Account - 1st Box Change / Question","day"),
array("NZ","Account - Access / Data Protection","email address"),
array("NZ","Account - Access / Data Protection","authorised"),
array("AU","Account - Access / Data Protection","mobile number"),
array("NZ","Account - Access / Data Protection","password"),
array("AU","Account - Access / Data Protection","email address"),
array("AU","Account - Access / Data Protection","unsubscribe"),
array("AU","Account - Access / Data Protection","typo"),
array("AU","Account - Access / Data Protection","password"),
array("NZ","Account - Access / Data Protection","unsubscribe"),
array("NZ","Account - Access / Data Protection","mobile number"),
array("AU","Account - Access / Data Protection","authorised"),
array("NZ","Account - Access / Data Protection","typo"),
array("AU","Account - After deadline change / cancellation request","deadline"),
array("AU","Account - After deadline change / cancellation request","delivery"),
array("AU","Account - After deadline change / cancellation request","change"),
array("AU","Account - After deadline change / cancellation request","refund"),
array("AU","Account - After deadline change / cancellation request","waive"),
array("NZ","Account - After deadline change / cancellation request","cancelled"),
array("NZ","Account - After deadline change / cancellation request","delivery"),
array("NZ","Account - After deadline change / cancellation request","meal swap"),
array("AU","Account - After deadline change / cancellation request","cancelled"),
array("NZ","Account - After deadline change / cancellation request","subscription"),
array("AU","Account - After deadline change / cancellation request","meal selection"),
array("NZ","Account - After deadline change / cancellation request","denied"),
array("AU","Account - After deadline change / cancellation request","denied"),
array("NZ","Account - After deadline change / cancellation request","deadline"),
array("NZ","Account - After deadline change / cancellation request","change"),
array("NZ","Account - After deadline change / cancellation request","lmc"),
array("NZ","Account - After deadline change / cancellation request","cutoff"),
array("NZ","Account - After deadline change / cancellation request","cancel"),
array("AU","Account - After deadline change / cancellation request","lmc"),
array("NZ","Account - After deadline change / cancellation request","address"),
array("AU","Account - After deadline change / cancellation request","address"),
array("NZ","Account - After deadline change / cancellation request","refund"),
array("AU","Account - After deadline change / cancellation request","subscription"),
array("NZ","Account - After deadline change / cancellation request","meal selection"),
array("AU","Account - After deadline change / cancellation request","meal swap"),
array("AU","Account - After deadline change / cancellation request","cutoff"),
array("AU","Account - After deadline change / cancellation request","cancel"),
array("NZ","Account - After deadline change / cancellation request","waive"),
array("NZ","Account - Cancellation","dup sub"),
array("NZ","Account - Cancellation","cancel"),
array("AU","Account - Cancellation","cancel"),
array("AU","Account - Cancellation","dup sub"),
array("AU","Account - Cancellation","deactivate"),
array("NZ","Account - Cancellation","sub dispute"),
array("AU","Account - Cancellation","sub dispute"),
array("AU","Account - Cancellation","duplicate"),
array("NZ","Account - Cancellation","duplicate"),
array("NZ","Account - Cancellation","deactivate"),
array("NZ","Account - Meal Swap / Recipe Preference / Questions","menu"),
array("AU","Account - Meal Swap / Recipe Preference / Questions","easter"),
array("AU","Account - Meal Swap / Recipe Preference / Questions","meal swap"),
array("AU","Account - Meal Swap / Recipe Preference / Questions","educated"),
array("NZ","Account - Meal Swap / Recipe Preference / Questions","educated"),
array("AU","Account - Meal Swap / Recipe Preference / Questions","preference"),
array("NZ","Account - Meal Swap / Recipe Preference / Questions","swap"),
array("NZ","Account - Meal Swap / Recipe Preference / Questions","default"),
array("AU","Account - Meal Swap / Recipe Preference / Questions","manual"),
array("NZ","Account - Meal Swap / Recipe Preference / Questions","preset"),
array("NZ","Account - Meal Swap / Recipe Preference / Questions","multiple up"),
array("AU","Account - Meal Swap / Recipe Preference / Questions","menu"),
array("AU","Account - Meal Swap / Recipe Preference / Questions","multiple up"),
array("NZ","Account - Meal Swap / Recipe Preference / Questions","preference"),
array("NZ","Account - Meal Swap / Recipe Preference / Questions","gluten"),
array("AU","Account - Meal Swap / Recipe Preference / Questions","preset"),
array("NZ","Account - Meal Swap / Recipe Preference / Questions","change"),
array("AU","Account - Meal Swap / Recipe Preference / Questions","swap"),
array("AU","Account - Meal Swap / Recipe Preference / Questions","default"),
array("NZ","Account - Meal Swap / Recipe Preference / Questions","manual"),
array("AU","Account - Meal Swap / Recipe Preference / Questions","gluten"),
array("NZ","Account - Meal Swap / Recipe Preference / Questions","meal swap"),
array("AU","Account - Meal Swap / Recipe Preference / Questions","change"),
array("NZ","Account - Meal Swap / Recipe Preference / Questions","easter"),
array("NZ","Account - Skip/Unskip","skipped"),
array("AU","Account - Skip/Unskip","donated"),
array("NZ","Account - Skip/Unskip","donated"),
array("AU","Account - Skip/Unskip","skipped"),
array("AU","Account - Skip/Unskip","info"),
array("AU","Account - Skip/Unskip","paused"),
array("NZ","Account - Skip/Unskip","info"),
array("NZ","Account - Skip/Unskip","paused"),
array("AU","Account - Skip/Unskip","unpaused"),
array("NZ","Account - Skip/Unskip","unpaused"),
array("NZ","Account - Subscription Settings / Questions","update card"),
array("NZ","Account - Subscription Settings / Questions","box type"),
array("AU","Account - Subscription Settings / Questions","box type"),
array("AU","Account - Subscription Settings / Questions","CP"),
array("NZ","Account - Subscription Settings / Questions","order history"),
array("AU","Account - Subscription Settings / Questions","FMB"),
array("NZ","Account - Subscription Settings / Questions","confirmation"),
array("NZ","Account - Subscription Settings / Questions","payment details"),
array("AU","Account - Subscription Settings / Questions","box plan"),
array("AU","Account - Subscription Settings / Questions","delivery"),
array("AU","Account - Subscription Settings / Questions","superbob"),
array("AU","Account - Subscription Settings / Questions","subscription"),
array("AU","Account - Subscription Settings / Questions","update card"),
array("NZ","Account - Subscription Settings / Questions","current plan"),
array("NZ","Account - Subscription Settings / Questions","box size"),
array("AU","Account - Subscription Settings / Questions","CB"),
array("AU","Account - Subscription Settings / Questions","classic"),
array("NZ","Account - Subscription Settings / Questions","classic"),
array("NZ","Account - Subscription Settings / Questions","reactivate"),
array("AU","Account - Subscription Settings / Questions","discount"),
array("AU","Account - Subscription Settings / Questions","price"),
array("NZ","Account - Subscription Settings / Questions","delivery"),
array("AU","Account - Subscription Settings / Questions","payment details"),
array("AU","Account - Subscription Settings / Questions","account"),
array("NZ","Account - Subscription Settings / Questions","discount"),
array("AU","Account - Subscription Settings / Questions","VB"),
array("NZ","Account - Subscription Settings / Questions","veggie"),
array("NZ","Account - Subscription Settings / Questions","subscription"),
array("NZ","Account - Subscription Settings / Questions","family"),
array("AU","Account - Subscription Settings / Questions","confirmation"),
array("AU","Account - Subscription Settings / Questions","plan size"),
array("AU","Account - Subscription Settings / Questions","switched"),
array("NZ","Account - Subscription Settings / Questions","account"),
array("AU","Account - Subscription Settings / Questions","order history"),
array("NZ","Account - Subscription Settings / Questions","CP"),
array("NZ","Account - Subscription Settings / Questions","queries"),
array("NZ","Account - Subscription Settings / Questions","VB"),
array("NZ","Account - Subscription Settings / Questions","box plan"),
array("AU","Account - Subscription Settings / Questions","settings"),
array("NZ","Account - Subscription Settings / Questions","price"),
array("AU","Account - Subscription Settings / Questions","second box"),
array("NZ","Account - Subscription Settings / Questions","box request"),
array("NZ","Account - Subscription Settings / Questions","FMB"),
array("AU","Account - Subscription Settings / Questions","family"),
array("NZ","Account - Subscription Settings / Questions","plan size"),
array("AU","Account - Subscription Settings / Questions","current plan"),
array("AU","Account - Subscription Settings / Questions","box request"),
array("NZ","Account - Subscription Settings / Questions","CB"),
array("AU","Account - Subscription Settings / Questions","queries"),
array("NZ","Account - Subscription Settings / Questions","superbob"),
array("NZ","Account - Subscription Settings / Questions","second box"),
array("AU","Account - Subscription Settings / Questions","veggie"),
array("NZ","Account - Subscription Settings / Questions","switched"),
array("AU","Account - Subscription Settings / Questions","reactivate"),
array("NZ","Account - Subscription Settings / Questions","settings"),
array("AU","Account - Subscription Settings / Questions","box size"),
array("NZ","All codes","verification"),
array("AU","All codes","verification"),
array("NZ","Complaint - Food Safety","foreign object"),
array("AU","Complaint - Food Safety","foreign object"),
array("NZ","Complaint - Food Safety","food safety report"),
array("AU","Complaint - Food Safety","food safety report"),
array("NZ","Complaint - Food Safety","poisoning"),
array("AU","Complaint - Food Safety","poisoning"),
array("NZ","Complaint - Logistics","on hold"),
array("AU","Complaint - Logistics","follow up needed"),
array("AU","Complaint - Logistics","re-delivery"),
array("AU","Complaint - Logistics","wrong address"),
array("AU","Complaint - Logistics","POD"),
array("NZ","Complaint - Logistics","property"),
array("NZ","Complaint - Logistics","wrong address"),
array("AU","Complaint - Logistics","Driver behaviour"),
array("NZ","Complaint - Logistics","re-delivery"),
array("NZ","Complaint - Logistics","instructions"),
array("NZ","Complaint - Logistics","tracking link"),
array("NZ","Complaint - Logistics","damaged property"),
array("AU","Complaint - Logistics","stolen"),
array("NZ","Complaint - Logistics","delayed"),
array("NZ","Complaint - Logistics","stolen"),
array("NZ","Complaint - Logistics","rescheduled"),
array("NZ","Complaint - Logistics","Driver behaviour"),
array("NZ","Complaint - Logistics","late"),
array("NZ","Complaint - Logistics","follow up needed"),
array("AU","Complaint - Logistics","damaged property"),
array("AU","Complaint - Logistics","no delivery"),
array("AU","Complaint - Logistics","on hold"),
array("AU","Complaint - Logistics","delayed"),
array("AU","Complaint - Logistics","late"),
array("AU","Complaint - Logistics","early"),
array("NZ","Complaint - Logistics","POD"),
array("NZ","Complaint - Logistics","quality"),
array("AU","Complaint - Logistics","rescheduled"),
array("AU","Complaint - Logistics","tracking link"),
array("AU","Complaint - Logistics","late"),
array("NZ","Complaint - Logistics","early"),
array("AU","Complaint - Logistics","quality"),
array("NZ","Complaint - Logistics","late"),
array("NZ","Complaint - Logistics","no delivery"),
array("NZ","Complaint - Logistics","neighbour"),
array("AU","Complaint - Logistics","instructions"),
array("AU","Complaint - Logistics","neighbour"),
array("AU","Complaint - Logistics","property"),
array("NZ","Complaint - Pick and Pack","incorrect"),
array("AU","Complaint - Pick and Pack","incorrect"),
array("NZ","Complaint - Pick and Pack","incorrect"),
array("AU","Complaint - Pick and Pack","missing"),
array("NZ","Complaint - Pick and Pack","missing"),
array("AU","Complaint - Pick and Pack","incorrect"),
array("NZ","Complaint - Pick and Pack","substitut"),
array("NZ","Complaint - Pick and Pack","hotwire"),
array("AU","Complaint - Pick and Pack","substitut"),
array("AU","Complaint - Pick and Pack","wrong"),
array("AU","Complaint - Pick and Pack","missing"),
array("NZ","Complaint - Pick and Pack","missing"),
array("AU","Complaint - Pick and Pack","hotwire"),
array("NZ","Complaint - Pick and Pack","wrong"),
array("NZ","Complaint - Quality","burst"),
array("NZ","Complaint - Quality","damage"),
array("NZ","Complaint - Quality","hotwire"),
array("NZ","Complaint - Quality","smelly"),
array("AU","Complaint - Quality","burst"),
array("AU","Complaint - Quality","rotten"),
array("NZ","Complaint - Quality","rotten"),
array("AU","Complaint - Quality","hotwire"),
array("NZ","Complaint - Quality","seal open"),
array("AU","Complaint - Quality","mouldy"),
array("NZ","Complaint - Quality","photo"),
array("AU","Complaint - Quality","photo"),
array("AU","Complaint - Quality","damage"),
array("AU","Complaint - Quality","seal open"),
array("AU","Complaint - Quality","smelly"),
array("NZ","Complaint - Quality","mouldy"),
array("AU","Complaint - Quality","spoiled"),
array("NZ","Complaint - Quality","spoiled"),
array("NZ","Complaint - Website / App / Internal Tech Error","system error"),
array("AU","Complaint - Website / App / Internal Tech Error","website"),
array("AU","Complaint - Website / App / Internal Tech Error","change not applied"),
array("AU","Complaint - Website / App / Internal Tech Error","system error"),
array("NZ","Complaint - Website / App / Internal Tech Error","website"),
array("AU","Complaint - Website / App / Internal Tech Error","BOB"),
array("NZ","Complaint - Website / App / Internal Tech Error","change not applied"),
array("AU","Complaint - Website / App / Internal Tech Error","app"),
array("NZ","Complaint - Website / App / Internal Tech Error","app"),
array("NZ","Complaint - Website / App / Internal Tech Error","BOB"),
array("AU","Connection Issue","unresponsive"),
array("NZ","Connection Issue","invalid"),
array("AU","Connection Issue","invalid"),
array("AU","Connection Issue","inactive"),
array("AU","Connection Issue","disconnect"),
array("NZ","Connection Issue","no response"),
array("NZ","Connection Issue","not responding"),
array("AU","Connection Issue","no response"),
array("NZ","Connection Issue","purecloud"),
array("AU","Connection Issue","not responding"),
array("NZ","Connection Issue","disconnect"),
array("NZ","Connection Issue","unresponsive"),
array("NZ","Connection Issue","inactive"),
array("AU","Connection Issue","purecloud"),
array("AU","Delivery - Account changes (Address / Window / Instructions)","time slot"),
array("AU","Delivery - Account changes (Address / Window / Instructions)","window"),
array("NZ","Delivery - Account changes (Address / Window / Instructions)","window"),
array("AU","Delivery - Account changes (Address / Window / Instructions)","address change"),
array("NZ","Delivery - Account changes (Address / Window / Instructions)","address change"),
array("AU","Delivery - Account changes (Address / Window / Instructions)","instructions"),
array("AU","Delivery - Account changes (Address / Window / Instructions)","delivery day"),
array("AU","Delivery - Account changes (Address / Window / Instructions)","frequency"),
array("NZ","Delivery - Account changes (Address / Window / Instructions)","time slot"),
array("AU","Delivery - Account changes (Address / Window / Instructions)","delivery notes"),
array("NZ","Delivery - Account changes (Address / Window / Instructions)","delivery notes"),
array("NZ","Delivery - Account changes (Address / Window / Instructions)","frequency"),
array("NZ","Delivery - Account changes (Address / Window / Instructions)","account holder"),
array("AU","Delivery - Account changes (Address / Window / Instructions)","delivery time"),
array("NZ","Delivery - Account changes (Address / Window / Instructions)","delivery day"),
array("NZ","Delivery - Account changes (Address / Window / Instructions)","instructions"),
array("AU","Delivery - Account changes (Address / Window / Instructions)","account holder"),
array("NZ","Delivery - Account changes (Address / Window / Instructions)","delivery time"),
array("AU","Delivery - Pending (window open)","ETA"),
array("NZ","Delivery - Pending (window open)","missed delivery window"),
array("AU","Delivery - Pending (window open)","late"),
array("NZ","Delivery - Pending (window open)","late"),
array("NZ","Delivery - Pending (window open)","ETA"),
array("NZ","Delivery - Pending (window open)","delayed"),
array("AU","Delivery - Pending (window open)","missed delivery window"),
array("AU","Delivery - Pending (window open)","delayed"),
array("AU","Marketing - Applied code to account","reactivation"),
array("NZ","Marketing - Applied code to account","reactivation"),
array("NZ","Marketing - Applied code to account","gift"),
array("AU","Marketing - Applied code to account","gift"),
array("AU","Marketing - Applied code to account","not applied"),
array("NZ","Marketing - Applied code to account","reactivated"),
array("NZ","Marketing - Applied code to account","not applied"),
array("NZ","Marketing - Applied code to account","manually"),
array("NZ","Marketing - Applied code to account","expired"),
array("AU","Marketing - Applied code to account","reactivated"),
array("AU","Marketing - Applied code to account","manually"),
array("AU","Marketing - Applied code to account","expired"),
array("NZ","Marketing - Direct Sales","ds"),
array("NZ","Marketing - Direct Sales","false email"),
array("AU","Marketing - Direct Sales","ds"),
array("NZ","Marketing - Direct Sales","misinformation"),
array("NZ","Marketing - Direct Sales","non customer"),
array("AU","Marketing - Direct Sales","non customer"),
array("NZ","Marketing - Direct Sales","serious complaint"),
array("AU","Marketing - Direct Sales","do not come back"),
array("AU","Marketing - Direct Sales","false email"),
array("AU","Marketing - Direct Sales","misinformation"),
array("AU","Marketing - Direct Sales","serious complaint"),
array("NZ","Marketing - Direct Sales","do not come back"),
array("NZ","Marketing - Other / Communication","email"),
array("AU","Marketing - Other / Communication","marketing campaign"),
array("AU","Marketing - Other / Communication","promotion"),
array("NZ","Marketing - Other / Communication","referral"),
array("AU","Marketing - Other / Communication","collaboration"),
array("AU","Marketing - Other / Communication","voucher"),
array("NZ","Marketing - Other / Communication","offer unclear"),
array("NZ","Marketing - Other / Communication","voucher"),
array("AU","Marketing - Other / Communication","3rd party"),
array("NZ","Marketing - Other / Communication","discount"),
array("AU","Marketing - Other / Communication","qantas"),
array("NZ","Marketing - Other / Communication","marketing campaign"),
array("NZ","Marketing - Other / Communication","promotion"),
array("AU","Marketing - Other / Communication","offer unclear"),
array("AU","Marketing - Other / Communication","hcf"),
array("AU","Marketing - Other / Communication","email"),
array("NZ","Marketing - Other / Communication","collaboration"),
array("AU","Marketing - Other / Communication","incorrect email"),
array("NZ","Marketing - Other / Communication","incorrect email"),
array("AU","Marketing - Other / Communication","discount"),
array("NZ","Marketing - Other / Communication","hcf"),
array("NZ","Marketing - Other / Communication","qantas"),
array("AU","Marketing - Other / Communication","referral"),
array("NZ","Marketing - Other / Communication","3rd party"),
array("NZ","Marketing - Referral","freebie"),
array("AU","Marketing - Referral","freebie"),
array("NZ","Marketing - Referral","helloshare"),
array("NZ","Marketing - Referral","new customer"),
array("AU","Marketing - Referral","existing customer"),
array("NZ","Marketing - Referral","existing customer"),
array("AU","Marketing - Referral","new customer"),
array("AU","Marketing - Referral","helloshare"),
array("AU","Marketing - Voucher Fraud","honored"),
array("NZ","Marketing - Voucher Fraud","incorrect"),
array("NZ","Marketing - Voucher Fraud","exception"),
array("AU","Marketing - Voucher Fraud","exception"),
array("AU","Marketing - Voucher Fraud","incorrect"),
array("AU","Marketing - Voucher Fraud","not honored"),
array("NZ","Marketing - Voucher Fraud","previous tenant"),
array("AU","Marketing - Voucher Fraud","previous tenant"),
array("NZ","Marketing - Voucher Fraud","not honored"),
array("NZ","Marketing - Voucher Fraud","honored"),
array("NZ","Marketing - Voucher not applied & compensated","rcad"),
array("NZ","Marketing - Voucher not applied & compensated","not applied"),
array("NZ","Marketing - Voucher not applied & compensated","refund after deadline"),
array("AU","Marketing - Voucher not applied & compensated","rcad"),
array("AU","Marketing - Voucher not applied & compensated","refunded and credited"),
array("AU","Marketing - Voucher not applied & compensated","honour"),
array("AU","Marketing - Voucher not applied & compensated","refund"),
array("NZ","Marketing - Voucher not applied & compensated","compensated"),
array("NZ","Marketing - Voucher not applied & compensated","honour"),
array("AU","Marketing - Voucher not applied & compensated","not applied"),
array("AU","Marketing - Voucher not applied & compensated","refund after deadline"),
array("NZ","Marketing - Voucher not applied & compensated","refund"),
array("NZ","Marketing - Voucher not applied & compensated","refunded and credited"),
array("AU","Marketing - Voucher not applied & compensated","compensated"),
array("AU","Other - Other / Business Query","business"),
array("NZ","Other - Other / Business Query","customer care error"),
array("NZ","Other - Other / Business Query","inquiry"),
array("NZ","Other - Other / Business Query","passed on details"),
array("NZ","Other - Other / Business Query","business"),
array("AU","Other - Other / Business Query","spam"),
array("AU","Other - Other / Business Query","customer care error"),
array("AU","Other - Other / Business Query","partnership"),
array("NZ","Other - Other / Business Query","feedback"),
array("NZ","Other - Other / Business Query","general"),
array("NZ","Other - Other / Business Query","partnership"),
array("AU","Other - Other / Business Query","vendor request"),
array("AU","Other - Other / Business Query","feedback"),
array("NZ","Other - Other / Business Query","vendor request"),
array("NZ","Other - Other / Business Query","spam"),
array("AU","Other - Other / Business Query","cc error"),
array("NZ","Other - Other / Business Query","cc error"),
array("AU","Other - Other / Business Query","inquiry"),
array("AU","Other - Other / Business Query","nan"),
array("AU","Other - Other / Business Query","general"),
array("NZ","Other - Other / Business Query","nan"),
array("AU","Other - Other / Business Query","passed on details"),
array("NZ","Other - Solved in previous interaction","no answer needed"),
array("AU","Other - Solved in previous interaction","thank you email"),
array("NZ","Other - Solved in previous interaction","thank you email"),
array("NZ","Other - Solved in previous interaction","solved"),
array("AU","Other - Solved in previous interaction","automatic reply"),
array("NZ","Other - Solved in previous interaction","automatic reply"),
array("AU","Other - Solved in previous interaction","no answer needed"),
array("NZ","Other - Solved in previous interaction","farewell"),
array("AU","Other - Solved in previous interaction","farewell"),
array("NZ","Other - Solved in previous interaction","thank"),
array("AU","Other - Solved in previous interaction","solved"),
array("AU","Other - Solved in previous interaction","thank"),
array("NZ","Other - Sustainability / Sourcing","vegan"),
array("AU","Other - Sustainability / Sourcing","packaging"),
array("NZ","Other - Sustainability / Sourcing","halal"),
array("AU","Other - Sustainability / Sourcing","recycling"),
array("NZ","Other - Sustainability / Sourcing","pick up request"),
array("NZ","Other - Sustainability / Sourcing","meat alternative"),
array("AU","Other - Sustainability / Sourcing","meat alternative"),
array("NZ","Other - Sustainability / Sourcing","plastic"),
array("AU","Other - Sustainability / Sourcing","suppliers"),
array("NZ","Other - Sustainability / Sourcing","recycling"),
array("NZ","Other - Sustainability / Sourcing","packaging"),
array("NZ","Other - Sustainability / Sourcing","suppliers"),
array("AU","Other - Sustainability / Sourcing","plastic"),
array("AU","Other - Sustainability / Sourcing","organic"),
array("AU","Other - Sustainability / Sourcing","vegan"),
array("AU","Other - Sustainability / Sourcing","pick up request"),
array("NZ","Other - Sustainability / Sourcing","organic"),
array("AU","Other - Sustainability / Sourcing","halal"),
array("AU","Payments - Charge breakdown query","refund query"),
array("AU","Payments - Charge breakdown query","premium"),
array("NZ","Payments - Charge breakdown query","premium"),
array("AU","Payments - Charge breakdown query","extras"),
array("NZ","Payments - Charge breakdown query","charge"),
array("AU","Payments - Charge breakdown query","confirmation"),
array("AU","Payments - Charge breakdown query","standard shipping"),
array("AU","Payments - Charge breakdown query","payment method"),
array("AU","Payments - Charge breakdown query","additional"),
array("NZ","Payments - Charge breakdown query","incorrect charge"),
array("NZ","Payments - Charge breakdown query","additional"),
array("NZ","Payments - Charge breakdown query","gourmet"),
array("NZ","Payments - Charge breakdown query","breakdown"),
array("NZ","Payments - Charge breakdown query","delivery fee"),
array("NZ","Payments - Charge breakdown query","confirmation"),
array("NZ","Payments - Charge breakdown query","confirming payment"),
array("NZ","Payments - Charge breakdown query","refund status"),
array("NZ","Payments - Charge breakdown query","payment method"),
array("AU","Payments - Charge breakdown query","region fee"),
array("AU","Payments - Charge breakdown query","refund status"),
array("AU","Payments - Charge breakdown query","charge"),
array("AU","Payments - Charge breakdown query","clarification"),
array("NZ","Payments - Charge breakdown query","refund query"),
array("AU","Payments - Charge breakdown query","gourmet"),
array("NZ","Payments - Charge breakdown query","clarification"),
array("AU","Payments - Charge breakdown query","payment breakdown"),
array("AU","Payments - Charge breakdown query","surcharge"),
array("AU","Payments - Charge breakdown query","dinner to lunch"),
array("NZ","Payments - Charge breakdown query","surcharge"),
array("NZ","Payments - Charge breakdown query","payment breakdown"),
array("NZ","Payments - Charge breakdown query","dinner to lunch"),
array("AU","Payments - Charge breakdown query","incorrect charge"),
array("NZ","Payments - Charge breakdown query","region fee"),
array("AU","Payments - Charge breakdown query","delivery fee"),
array("NZ","Payments - Charge breakdown query","standard shipping"),
array("AU","Payments - Charge breakdown query","fresh & fast"),
array("AU","Payments - Charge breakdown query","charge twice"),
array("NZ","Payments - Charge breakdown query","extras"),
array("AU","Payments - Charge breakdown query","breakdown"),
array("NZ","Payments - Charge breakdown query","proof of payment"),
array("NZ","Payments - Charge breakdown query","charge twice"),
array("AU","Payments - Charge breakdown query","confirming payment"),
array("NZ","Payments - Charge breakdown query","fresh & fast"),
array("AU","Payments - Charge breakdown query","proof of payment"),
array("NZ","Payments - Confirmation that credit has applied to account","credit"),
array("NZ","Payments - Confirmation that credit has applied to account","confirmed refund"),
array("AU","Payments - Confirmation that credit has applied to account","confirmed refund"),
array("NZ","Payments - Confirmation that credit has applied to account","confirmed credit"),
array("AU","Payments - Confirmation that credit has applied to account","credit"),
array("NZ","Payments - Confirmation that credit has applied to account","confirmed"),
array("AU","Payments - Confirmation that credit has applied to account","confirmed credit"),
array("AU","Payments - Confirmation that credit has applied to account","confirmed"),
array("NZ","Payments - Failed payment","already resolved"),
array("AU","Payments - Failed payment","goodwill waive"),
array("AU","Payments - Failed payment","payments form"),
array("AU","Payments - Failed payment","complaint"),
array("NZ","Payments - Failed payment","debt collection"),
array("NZ","Payments - Failed payment","outstanding"),
array("NZ","Payments - Failed payment","goodwill waive"),
array("AU","Payments - Failed payment","extension"),
array("AU","Payments - Failed payment","payment method"),
array("AU","Payments - Failed payment","bank transfer details"),
array("NZ","Payments - Failed payment","payment method"),
array("NZ","Payments - Failed payment","payments form"),
array("AU","Payments - Failed payment","payments schedule"),
array("NZ","Payments - Failed payment","bank transfer details"),
array("AU","Payments - Failed payment","payment plan"),
array("AU","Payments - Failed payment","outstanding"),
array("NZ","Payments - Failed payment","payments schedule"),
array("AU","Payments - Failed payment","debt collection"),
array("AU","Payments - Failed payment","already resolved"),
array("NZ","Payments - Failed payment","complaint"),
array("NZ","Payments - Failed payment","payment plan"),
array("NZ","Payments - Failed payment","extension"),
array("NZ","Payments - Question / Other","late payment"),
array("NZ","Payments - Question / Other","payments form"),
array("NZ","Payments - Question / Other","inquiry"),
array("AU","Payments - Question / Other","escalated"),
array("AU","Payments - Question / Other","transferred"),
array("NZ","Payments - Question / Other","transferred"),
array("NZ","Payments - Question / Other","specialist"),
array("AU","Payments - Question / Other","late payment"),
array("NZ","Payments - Question / Other","charge"),
array("AU","Payments - Question / Other","payments form"),
array("NZ","Payments - Question / Other","outstanding"),
array("NZ","Payments - Question / Other","escalated"),
array("AU","Payments - Question / Other","specialist"),
array("AU","Payments - Question / Other","charge"),
array("NZ","Payments - Question / Other","payment plan"),
array("AU","Payments - Question / Other","payment plan"),
array("AU","Payments - Question / Other","inquiry"),
array("AU","Payments - Question / Other","outstanding"),
array("NZ","Payments - SIFT Exceptions List","error message"),
array("AU","Payments - SIFT Exceptions List","error message"),
array("NZ","Payments - SIFT Exceptions List","fraud"),
array("AU","Payments - SIFT Exceptions List","fraud"),
array("AU","Payments - SIFT Exceptions List","clear browsing"),
array("AU","Payments - SIFT Exceptions List","incognito"),
array("NZ","Payments - SIFT Exceptions List","already placed"),
array("AU","Payments - SIFT Exceptions List","exception"),
array("NZ","Payments - SIFT Exceptions List","SIFT"),
array("NZ","Payments - SIFT Exceptions List","incognito"),
array("NZ","Payments - SIFT Exceptions List","clear browsing"),
array("NZ","Payments - SIFT Exceptions List","exception"),
array("AU","Payments - SIFT Exceptions List","already placed"),
array("AU","Payments - SIFT Exceptions List","SIFT")
)) as col)
"""
