from . import aaa_get_dates
from  . import stage1_Raw_FCR
from  . import stage2_User_FCR_KPI_Data
from  . import stage3_User_AHT_KPI_Data
from  . import stage4_Call_Volume
from  . import stage5_User_Details
from  . import stage6_JSR_KPI_User_Team_Target
from  . import stage7_JSR_Process_Forecast_Data
from  . import stage8_JSR_KPI_Team_Target
from  . import stage9_User_KPI_Data
from  . import stage10_JSR_Top_Reason_Data
from  . import stage11_JSR_Process_TNPS_KPI_Data_to_All_Process
from  . import stage12_Process_AHT_KPI_Data_to_All_Process
from  . import stage13_JSR_Process_KPI_Data_to_All_Process
from  . import stage14_JSR_Process_FCR_KPI_to_All_Process
from  . import stage15_Admin_Login
from  . import stage16_JSR_AHT_KPI_Data
from  . import stage17_JSR_Trouble_Ticket_Data
from  . import stage18_JSR_Process_KPI_Data
