aggr_pipeline = [{'$addFields': {'fcr': {'$cond': {'if': {'$eq': ['$check', 'FCR']},
     'then': 1.0,
     'else': 0.0}},
   'total': 1.0}},
 {'$group': {'_id': {'user_id': '$user_id',
    'report_date': {'$dateToString': {'format': '%Y-%m-%d',
      'date': '$report_date'}}},
   'fcr_count': {'$sum': '$fcr'},
   'total_calls': {'$sum': '$total'}}},
 {'$lookup': {'from': 'user_details',
   'localField': '_id.user_id',
   'foreignField': 'siebel_id',
   'as': 'user'}},
 {'$unwind': {'path': '$user', 'preserveNullAndEmptyArrays': True}},
 {'$project': {'siebel_id': '$_id.user_id',
   'user_id': '$user.cms_name',
   'date': '$_id.report_date',
   'value1': '$fcr_count',
   'value2': '$total_calls',
   'kpi': 'FCR',
   '_id': 0.0}}]