aggr_pipeline = [{'$addFields': {'report_date': {'$substr': ['$report_date', 0.0, 10.0]},
   'TNPS_VAL': {'$switch': {'branches': [{'case': {'$and': [{'$gte': ['$overall_tnps',
           0.0]},
         {'$lt': ['$overall_tnps', 7.0]}]},
       'then': 'Detractor'},
      {'case': {'$and': [{'$gte': ['$overall_tnps', 9.0]},
         {'$lt': ['$overall_tnps', 11.0]}]},
       'then': 'Promoter'},
      {'case': {'$and': [{'$gte': ['$overall_tnps', 7.0]},
         {'$lt': ['$overall_tnps', 9.0]}]},
       'then': 'Passive'}],
     'default': ''}}}},
 {'$group': {'_id': {'user': '$user_id', 'report_date': '$report_date'},
   'Detractor': {'$sum': {'$cond': [{'$eq': ['$TNPS_VAL', 'Detractor']},
      1.0,
      0.0]}},
   'Promoter': {'$sum': {'$cond': [{'$eq': ['$TNPS_VAL', 'Promoter']},
      1.0,
      0.0]}},
   'Passive': {'$sum': {'$cond': [{'$eq': ['$TNPS_VAL', 'Passive']},
      1.0,
      0.0]}},
   'FCR': {'$sum': {'$cond': [{'$eq': ['$issue_resolved',
        'Yes, on the first time I contacted Vodafone']},
      1.0,
      0.0]}},
   'NFCR': {'$sum': {'$cond': [{'$or': [{'$eq': ['$issue_resolved', 'No']},
        {'$eq': ['$issue_resolved',
          'Yes, but I had to contact Vodafone more than once']}]},
      1.0,
      0.0]}}}},
 {'$lookup': {'from': 'user_details',
   'localField': '_id.user',
   'foreignField': 'siebel_id',
   'as': 'user'}},
 {'$unwind': {'path': '$user', 'preserveNullAndEmptyArrays': True}},
 {'$facet': {'TNPS': [{'$project': {'siebel_id': '$_id.user',
      'user_id': '$user.cms_name',
      'date': '$_id.report_date',
      'value1': {'$subtract': ['$Promoter', '$Detractor']},
      'value2': {'$add': ['$Promoter', '$Detractor', '$Passive']},
      'kpi': 'TNPS',
      '_id': 0.0}}],
   'FTF': [{'$project': {'siebel_id': '$_id.user',
      'user_id': '$user.cms_name',
      'date': '$_id.report_date',
      'value1': '$FCR',
      'value2': {'$add': ['$FCR', '$NFCR']},
      'kpi': 'FTF',
      '_id': 0.0}}]}},
 {'$project': {'common': {'$concatArrays': ['$TNPS', '$FTF']}}},
 {'$unwind': {'path': '$common'}},
 {'$project': {'user_id': '$common.user_id',
   'siebel_id': '$common.siebel_id',
   'date': '$common.date',
   'value1': '$common.value1',
   'value2': '$common.value2',
   'kpi': '$common.kpi'}}]