def fact_contacts_completed(spark):
    spark.sql(
        """
        INSERT INTO spark_catalog.niceincontact_infobell.fact_contacts_completed
        SELECT
            contactId,
            agentId,
            skillId,
            teamId,
            campaignId,
            primaryDispositionId,
            secondaryDispositionId,
            abandoned,
            abandonSeconds,
            acwSeconds,
            agentSeconds,
            callbackTime,
            conferenceSeconds,
            holdSeconds,
            holdCount,
            inQueueSeconds,
            postQueueSeconds,
            preQueueSeconds,
            releaseSeconds,
            totalDurationSeconds,
            serviceLevelFlag,
            isOutbound,
            isRefused,
            isShortAbandon,
            highProficiency,
            lowProficiency,
            extractDate,
            extractIntervalStartTime,
            extractIntervalEndTime,
            recordInsertTime,
            recordIdentifier
        FROM spark_catalog.niceincontact_infobell.raw_contacts_completed
        """
    )